GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Models/Turma.cs
namespace GerenciadorTurma.FrontEnd.Models
{
    public class Turma : BaseEntity
    {
        public int Curso_id { get; set; }
        public string turma { get; set; }
        public int Ano { get; set; }
    }
}

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorTurma.FrontEnd.Data;
using GerenciadorTurma.FrontEnd.Models;
using GerenciadorTurma.FrontEnd.Models.Interfaces;
using System.Text.RegularExpressions;
using Microsoft.IdentityModel.Tokens;

namespace GerenciadorTurma.FrontEnd.Controllers
{
    public class AlunosController : Controller
    {
        private readonly IAlunoService _service;

        public AlunosController(IAlunoService alunoService)
        {
            _service = alunoService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _service.BuscarTodosAlunos());
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _service.BuscarAluno(id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,Usuario,senha")] Aluno aluno)
        {
           if (ModelState.IsValid)
            {
                if (!ValidarSenhaAluno(aluno))
                {
                    ViewBag.MensagemErro = "A senha não atende aos critérios de segurança.";
                    return View();
                }

                if (aluno.Nome.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo Nome";
                    return View();
                }

                if (aluno.Usuario.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo Usuario";
                    return View();
                }

                await _service.CriarAluno(aluno);
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _service.BuscarAluno(id);
            if (aluno == null)
            {
                return NotFound();
            }
            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Nome,Usuario,senha, Id")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                if (aluno.Nome.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo Nome";
                    return View();
                }

                if (aluno.Usuario.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo Usuario";
                    return View();
                }

                await _service.EditarAluno(aluno);
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _service.ApagarAluno(id);
            if (aluno == null)
            {
                return NotFound();
            }

            return RedirectToAction("index");
        }

        public bool ValidarSenhaAluno(Aluno aluno)
        {
            if (aluno.senha.Length < 8)
                return false;

            if (!Regex.IsMatch(aluno.senha, @"\d"))
                return false;

            if (!Regex.IsMatch(aluno.senha, @"[!@#$%^&*()_+{}\[\]:;<>,.?~]"))
                return false;

            if (!Regex.IsMatch(aluno.senha, @"[A-Z]"))
                return false;

            if (!Regex.IsMatch(aluno.senha, @"[a-z]"))
                return false;

            return true;
        }

    }
}

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Controllers/TurmasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GerenciadorTurma.FrontEnd.Data;
using GerenciadorTurma.FrontEnd.Models;
using GerenciadorTurma.FrontEnd.Models.Interfaces;
using Microsoft.IdentityModel.Tokens;

namespace GerenciadorTurma.FrontEnd.Controllers
{
    public class TurmasController : Controller
    {
        private readonly ITurmaService _service;

        public TurmasController(ITurmaService TurmaService)
        {
            _service = TurmaService;
        }

        // GET: Turmas
        public async Task<IActionResult> Index()
        {
            return View(await _service.BuscarTodosTurmas());
        }

        // GET: Turmas/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Turma = await _service.BuscarTurma(id);
            if (Turma == null)
            {
                return NotFound();
            }

            return View(Turma);
        }

        // GET: Turmas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turmas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Curso_id,turma,Ano")] Turma turm)
        {
            if (ModelState.IsValid)
            {
                if (turm.Curso_id <= 0)
                {
                    ViewBag.MensagemErro = "O id deve ser maior que 0";
                    return View();
                }

                if (turm.turma.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo turma";
                    return View();
                }

                if (turm.Ano < 1000 || turm.Ano > 9999)
                {
                    ViewBag.MensagemErro = "Digite um ano com 4 dígitos";
                    return View();
                }

                if (turm.Ano < DateTime.Now.Year)
                {
                    ViewBag.MensagemErro = "Digite um ano que seja maior ou igual o atual";
                    return View();
                }

                await _service.CriarTurma(turm);
                return RedirectToAction(nameof(Index));
            }
            return View(turm);
        }

        // GET: Turmas/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Turma = await _service.BuscarTurma(id);
            if (Turma == null)
            {
                return NotFound();
            }
            return View(Turma);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Curso_id,turma,Ano,Id")] Turma turm)
        {
            if (ModelState.IsValid)
            {
                if (turm.Curso_id <= 0)
                {
                    ViewBag.MensagemErro = "O id deve ser maior que 0";
                    return View();
                }

                if (turm.turma.IsNullOrEmpty())
                {
                    ViewBag.MensagemErro = "Preencha o campo turma";
                    return View();
                }

                if (turm.Ano < 1000 || turm.Ano > 9999)
                {
                    ViewBag.MensagemErro = "Digite um ano com 4 dígitos";
                    return View();
                }

                if (turm.Ano < DateTime.Now.Year)
                {
                    ViewBag.MensagemErro = "Digite um ano que seja maior ou igual o atual";
                    return View();
                }



                await _service.EditarTurma(turm);
                return RedirectToAction(nameof(Index));
            }
            return View(turm);
        }


        // POST: Turmas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.


        // GET: Turmas/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Turma = await _service.ApagarTurma(id);
            if (Turma == null)
            {
                return NotFound();
            }

            return RedirectToAction("index");
        }

        public async Task<IActionResult> ListaAlunosTurma(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Turma = await _service.BuscarAlunosEmTurma(id);
            if (Turma == null)
            {
                return NotFound();
            }
            return View(Turma);
        }

        public async Task<IActionResult> RemoverAlunoDeTurma(int idAluno, int idTurma)
        {
            if (idAluno == null && idTurma == null)
            {
                return NotFound();
            }

            var Turma = await _service.RemoverAlunoDeTurma(idAluno, idTurma);
            if (Turma == null)
            {
                return NotFound();
            }

            return RedirectToAction("ListaAlunosTurma", new { id = idTurma });
        }

        public async Task<IActionResult> AdicionarAlunoaTurma(int idAluno, int idTurma)
        {
            if (idAluno == null && idTurma == null)
            {
                return NotFound();
            }

            var Turma = await _service.AdicionarAlunoaTurma(idAluno, idTurma);
            if (Turma == null)
            {
                return NotFound();
            }

            return RedirectToAction("ListaAlunosTurma",  new {id = idTurma});
        }

    }
}

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/Create.cshtml
@model GerenciadorTurma.FrontEnd.Models.Turma

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<h4>Turma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Curso_id" class="control-label"></label>
                <input asp-for="Curso_id" class="form-control" />
                <span asp-validation-for="Curso_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @if (!string.IsNullOrEmpty(ViewBag.MensagemErro))
            {
                <span class="text-danger">@ViewBag.MensagemErro</span>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/Delete.cshtml
@model GerenciadorTurma.FrontEnd.Models.Turma

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>
    Tem certeza que deseja apagar?</h3>
<div>
    <h4>Turma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.turma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/Details.cshtml
@model GerenciadorTurma.FrontEnd.Models.Turma

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Turma</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Curso_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Curso_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.turma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/Edit.cshtml
@model GerenciadorTurma.FrontEnd.Models.Turma

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Turma</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Curso_id" class="control-label"></label>
                <input asp-for="Curso_id" class="form-control" />
                <span asp-validation-for="Curso_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="turma" class="control-label"></label>
                <input asp-for="turma" class="form-control" />
                <span asp-validation-for="turma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            @if (!string.IsNullOrEmpty(ViewBag.MensagemErro))
            {
                <span class="text-danger">@ViewBag.MensagemErro</span>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/Index.cshtml
@model IEnumerable<GerenciadorTurma.FrontEnd.Models.Turma>

@{
    ViewData["Title"] = "Index";
}

<h1>Turmas</h1>

<p>
    <a asp-action="Create">Criar nova turma</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Curso Id
            </th>
            <th>
                Turma
            </th>
            <th>
                Ano
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Curso_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.turma)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a> |
                    <a asp-action="ListaAlunosTurma" asp-route-id="@item.Id">Alunos Cadastrados</a>
            </td>
        </tr>
}
    </tbody>
</table>

GerenciadorTurma.FrontEnd/GerenciadorTurma.FrontEnd/Views/Turmas/ListaAlunosTurma.cshtml
@model GerenciadorTurma.FrontEnd.Models.AlunoTurma

@{
    ViewData["Title"] = "Turma";
}

<h1>Turma @Model.Turma.turma.ToString()</h1>

<h3>Turma</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Turma
            </th>
            <th>
                Curso Id
            </th>
            <th>
                Ano
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Turma.Id)
            </td>
            <td>
                @Html.DisplayFor(model => model.Turma.turma)
            </td>
            <td>
                @Html.DisplayFor(model => model.Turma.Curso_id)
            </td>
             <td>
               @Html.DisplayFor(model => model.Turma.Ano)
            </td>
            <td></td>
        </tr>
    </tbody>
</table>


<br />
<br />
<h3>Alunos cadastrados</h3>
<table class="table">
    <thead>
        <tr>
            <th>
               Nome
            </th>
            <th>
                Usuario
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Alunos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
              <a asp-action="RemoverAlunoDeTurma" asp-route-idAluno="@item.Id" asp-route-idTurma="@Model.Turma.Id">Remover da turma</a> |
            </td>
        </tr>
}
    </tbody>
</table>

<br /><br />
<h3>Alunos não cadastrados</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Usuario
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AlunosForaDaTurma)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Usuario)
                </td>
                <td>
                    <a asp-action="AdicionarAlunoaTurma" asp-route-idAluno="@item.Id" asp-route-idTurma="@Model.Turma.Id">Adicionar a turma</a> |
                    <a asp-controller="Alunos" asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                </td>
            </tr>
        }
    </tbody>
</table>